name: Run Pytest
on:
  schedule:
    - cron: "5 4 * * *"
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/setup-lxd@main
      - run: curl --unix-socket /var/snap/lxd/common/lxd/unix.socket http://localhost/1.0
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry install
      - run: poetry run pytest -vvvvvv --exitfirst --random-order --random-order-bucket=global
